files:
  - source: /src/messages/en.json
    translation: /src/messages/%two_letters_code%.json
    languages_mapping:
      two_letters_code:
        es-ES: es
        fr-BE: be
        de-AT: at
        zh-TW: tw
