files:
  - source: /src/messages/en.json
    translation: /src/messages/%locale%.json
    languages_mapping:
      locale:
        de: de
        fr: fr
        it: it
        es-ES: es
        nl: nl
        fr-BE: be
        de-AT: at
        zh-TW: tw
